name: "Deploy to Penguin Staging"
run-name: Deploy Penguin Content and Metadata from ${{ github.ref_name }} to Staging

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy to Penguin (Staging)
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy content
        env:
          PENGUINCTL_APIURL: ${{ secrets.PENGUINCTL_APIURL }}
          PENGUINCTL_APITOKEN: ${{ secrets.PENGUINCTL_APITOKEN }}
        run: |
          cd spring-academy
          make deploy
